language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
install: mvn -Pbuild-swagger-documentation -DskipTests=true -B -faeq install
script: mvn -B -faeq verify

git:
  depth: 100

sudo: false

