language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

install: mvn -Pbuild-swagger-documentation -DskipTests=true -DskipSingularityWebUI -B -q -fae install
script: mvn -DskipSingularityWebUI -B -q -fae verify

git:
  depth: 100

sudo: false

cache:
  directories:
  - $HOME/.m2
